apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-t4rt
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-t4rt
    app.kubernetes.io/part-of: ci10t-776-0087-app
  name: devfile-sample-t4rt
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-t4rt
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-t4rt
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0087-tenant/ci10t-776-0087-app/devfile-sample-t4rt@sha256:cc3c4dff14192985056625f22071da3014c170a2643738bb8d5cc642bdf373ed
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
